drop table if exists bookmarks;

create table bookmarks (
  id INTEGER primary key generated by default as identity,
  website TEXT,
  summary TEXT,
  rating INTEGER
);

insert into bookmarks (website, summary, rating)
values
  ('https://youtube.com', 'videos', 4),
  ('https://gmail.com', 'mail', 2),
  ('https://ign.com', 'game', 4),
  ('https://goodgood.com', 'good', 3),
  ('https://oooweewow.com', 'woah', 4),
  ('https://zoooweeemama.com', 'wow', 1),
  ('https://seinfeld.com', 'funny', 5),
  ('https://freshprince.com', 'also funny', 5),
  ('https://home.com', 'home', 5),
  ('https://target.com', 'shop', 3);
